// Golden parity test. Every case in MATRIX is checked against a *committed
// literal* string in goldens.json (generated by the now-deleted
// test/gen-goldens.mjs from the real vendored Day.js, back when Day.js still
// existed) - never a dual-run comparison - so this suite keeps working
// unchanged now that Day.js is gone.
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { MATRIX } from './matrix.mjs';
import goldens from './goldens.json' with { type: 'json' };

const require = createRequire(import.meta.url);
const { getFormattedString: fmt } = require('../scripts/formatter.js');

for (const c of MATRIX) {
  test(`golden: ${c.id}`, () => {
    const date = new Date(c.ts * 1000);
    const actual = fmt(date, c.tz, c.format, c.includeRegion);
    assert.equal(actual, goldens[c.id]);
  });
}

test('golden: invalid timezone throws RangeError', () => {
  assert.throws(() => fmt(new Date(0), 'Nope/Zip', 'YYYY'), RangeError);
});

test('golden: invalid date renders literal "Invalid Date" plus region', () => {
  const actual = fmt(new Date(NaN), 'America/New_York', 'YYYY', true);
  assert.equal(actual, 'Invalid Date - New York');
});
